# Generated by Django 6.1 on 2026-09-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Prime Flow', max_length=100)),
                ('slogan', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('founded_year', models.IntegerField()),
                ('mission', models.TextField()),
                ('values', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('working_hours', models.CharField(max_length=100)),
            ],
        ),
    ]
