# Generated by Django 6.1.1 on 2026-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='received_at',
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
